### DISCUSSION TITLE
Trait for `Responder<'_,'_>` not satisfied

### DISCUSSION THREAD

**Discussion by aditya-mitra** [rwf2/Rocket#1819] [Questions] [answered]
I am very new to Rust and I encountered this error while try to build a simple web server using Rocket.

I have the following code:

```rs
use rocket_contrib::json::Json;
use serde::{Serialize,Deserialize};

#[derive(Serialize,Deserialize)]
struct NotFound {
    success: bool,
    message: String,
}

#[get("/_/admin", format = "json")]
pub fn index() -> Json<NotFound> {
    Json(NotFound {
        success: false,
        message: String::from("Not Found Custom 404"),
    })
}
```

On compilation, it gives me the following error:

**the trait bound `rocket_contrib::json::Json<routes::index_route::NotFound>: rocket::response::Responder<'_, '_>` is not satisfied**

![image](https://user-images.githubusercontent.com/55396651/129360113-dc7cf071-7572-4f2c-be1d-a00ebbfe7fd6.png)

The dependencies in my _cargo.toml_ are as follows:

```toml
[package]
name = "server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
```

Can somebody please help me with what mistake I am making?
