### DISCUSSION TITLE
How can I read the Rocket.toml?

### DISCUSSION THREAD

**Discussion by knota-lab** [rwf2/Rocket#1909] [Questions] [answered]
I read `Rocket.toml` in `AdHoc::on_liftoff` got an error. I don't understand how the `Rocket.toml` is read in the document.

version info:
rocket = {version = "0.5.0-rc.1", features = ["secrets", "tls", "json"]}

```rust
    rocket::build()
        .manage(es_client)
        .attach(database::MysqlDBConn::fairing())
        .attach(fairing::CORS)
        .attach(AdHoc::on_liftoff("nacos", |rocket| {
            let figment = rocket.figment();
            println!("{:?}", figment.extract_inner::<String>("nacos"));
            Box::pin(async move {
                tokio::spawn(async move {
                    let mut interval = tokio::time::interval(Duration::from_secs(5));
                    loop {
                        interval.tick().await;
                        println!("@@@@@@@@@@@@@@@@@@@@");
                    }
                });
            })
        }))
```

```toml
[global.databases]
mysql = { url = "mysql://root:root@localhost:3306/rocket_document_manager" }

# [nacos]
nacos = "localhost:8848"
```

```
Err(Error { tag: Tag::Default, profile: None, metadata: None, path: [], kind: MissingField("nacos"), prev: None })
```

**Comment by knota-lab** [comment, marked as answer]
use `figment.find_value("databases");` to access the config.

**Reply by knota-lab** [reply]
```toml
[global.databases]
mysql = { url = "mysql://root:root@localhost:3306/rocket_document_manager" }

[global.nacos]
host = "localhost:8848"
```

```rust
let rocket = rocket::build();
let figment = rocket.figment();

let figment = figment.focus("nacos");
println!("{:?}", figment.extract_inner::<String>("host"));
```
