### DISCUSSION TITLE
`Responder` Trait for `diesel::result::Error` not satisfied

### DISCUSSION THREAD

**Discussion by Glitchy-Tozier** [rwf2/Rocket#2163] [Questions] [answered]
I wrote an error-enum to help me use the `?`-operator elegantly. However, I receive errors like this:
```
the trait bound `diesel::result::Error: rocket::response::Responder<'_, '_>` is not satisfied
the trait `rocket::response::Responder<'_, '_>` is not implemented for `diesel::result::Error`

the trait bound `validator::ValidationError: rocket::response::Responder<'_, '_>` is not satisfied
the trait `rocket::response::Responder<'_, '_>` is not implemented for `validator::ValidationError`
```

I'm not quite sure what to do. I'm unable to impl or derive `Responder` for those errors.

Rust-code:

```rs
use std::{
    error::Error,
    fmt::{self, Display, Formatter},
    result::Result,
};

pub type HandlerResult<T> = Result<T, HandlerError>;

#[derive(Debug, Responder)]
#[response(status = 500, content_type = "json")]
pub enum HandlerError {
    //#[response(status = 500, content_type = "json")]
    Validation(validator::ValidationError),
    Diesel(diesel::result::Error),
    Io(std::io::Error),
    Text(String),
}

impl Error for HandlerError {}

impl Display for HandlerError {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        write!(f, "{}", self)
    }
}
```

---

I also receive this error, but I suspect it has more to do with `rocket_ok_api`. Still, I'd highly appreciate getting tips on how to approach this issue.
```
the trait bound `errors::HandlerError: rocket_okapi::response::OpenApiResponderInner` is not satisfied
required because of the requirements on the impl of `rocket_okapi::response::OpenApiResponderInner` for `std::result::Result<rocket::serde::json::Json<(std::string::String, std::string::String)>, errors::HandlerError>`
required because of the requirements on the impl of `rocket_okapi::response::OpenApiResponder<'_, '_>` for `std::result::Result<rocket::serde::json::Json<(std::string::String, std::string::String)>, errors::HandlerError>`
```

**Comment by Glitchy-Tozier** [comment]
My dependencies:

```toml
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.8", features = ["postgres", "chrono", "serde_json"] }
okapi = "0.7.0-rc.1"
rand = "0.8.5"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
rocket_okapi = { version = "0.8.0-rc.1", features = ["swagger"] }
schemars = { version = "0.8.8", features = ["chrono"] }
serde = { version = "^1.0", features = ["derive"] }
validator = { version = "0.15", features = ["derive"] }
```
