### DISCUSSION TITLE
How do i setup Rocket with redis + connection pool?

### DISCUSSION THREAD

**Discussion by patchthecode** [rwf2/Rocket#2253] [General]
How do i setup Rocket with redis + connection pool?

The documentation wasnt very clear for me, and tutorials online do not work for version `0.5.0-rc.2`
Could you provide an example or guide me to what documentation i should look at that gives a redis example?  Many of the examples use SQL

**Comment by ELD** [comment]
Are you wanting to set up a connection pool for Redis or do you want both a connection pool for Redis and a separate connection pool for a No/SQL database (e.g. Postgres, MongoDB, etc)?

For either, using Rocket `0.5.0-rc.2`, you should be good to use the `rocket_db_pools` crate.

(I'm assuming you want Redis _and_ a SQL database connection pool)
(Also, I haven't tested this, so some things may be slightly incorrect or `use` paths might be wrong)

In your Cargo.toml:
```toml
# ...
[dependencies]
rocket = "0.5.0-rc.2"
rocket_db_pools = { version = "0.1.0-rc.2", features = [ "deadpool_redis", "sqlx_postgres" ] }
# ...
```

Now in your `main.rs` (or similar, or separate modules, depending on code organization)
```rust
use rocket_db_pools::{Connection, Database, deadpool_redis, sqlx};
use rocket::{launch, get};

#[derive(Database)]
#[database("redis_pool")]
pub RedisPool(deadpool_redis::Pool);

#[derive(Database)]
#[database("postgres_pool")]
pub PostgresPool(sqlx::PgPool);

#[get("/")]
async fn test_route(redis: Connection<RedisPool>, pg: Connection<PostgresPool>) {
    // ...
}

#[launch]
fn rocket() -> _ {
    rocket::ignite()
        .attach(RedisPool::init())
        .attach(PostgresPool::init())
}
```

Finally, either in environment variables or in your `Rocket.toml`:
```toml
[default.databases.redis_pool]
url = "..."

[default.databases.postgres_pool]
url = "..."
```

In general, review the `rocket_db_pools` docs for more information and a basic example using SQLite (it's very similar for Redis): https://api.rocket.rs/v0.5-rc/rocket_db_pools/index.html
