### DISCUSSION TITLE
no function or associated item named `pool` found for struct `ConnectionPool` in the current scope

### DISCUSSION THREAD

**Discussion by blackghost1987** [rwf2/Rocket#2522] [Questions] [answered]
I'm setting up a new Rocket project, mostly copy-pasting from and old one, and I keep getting this error when I'm trying to add my Database fairing.

```
error[E0599]: no function or associated item named `pool` found for struct `ConnectionPool` in the current scope
 --> src\database.rs:7:1
   |
17 | #[database("property_db")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
   | |
   | function or associated item not found in `ConnectionPool<Db, PgConnection>`
   | help: there is an associated function with a similar name: `get_pool`
   |
   = note: this error originates in the attribute macro `database` (in Nightly builds, run with -Z macro-backtrace for more info)
   ```
   
I'm pretty sure this is not a bug and I just messed up something trivial, because I have this exact setup with Diesel and Postgresql in my other project and it's working fine there. Either way, the error message is really not helpful, so I'm pretty stuck.

**database.rs:**
```rust
use diesel::prelude::*;
use diesel::PgConnection;
use rocket_sync_db_pools::database;

pub type Conn = PgConnection;

#[database("property_db")]
pub struct Db(Conn);
```

**main.rs:**
```rust
#[macro_use]
extern crate rocket;
#[macro_use]
extern crate diesel;

mod database;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[launch]
fn rocket() -> _ {
    rocket::build()
        .attach(database::Db::fairing())
        .mount("/", routes![index])
}
```

**Rocket.toml:**
```toml
[global.databases.property_db]
url = "postgresql://...localhost:5432/...."
```

**Cargo.toml:**
```toml
[dependencies]
diesel = { version = "1.4", default-features = false, features = ["postgres", "chrono", "64-column-tables", "serde_json"] }
diesel_migrations = "1.4.0"
rocket = { version = "=0.5.0-rc.2", features = ["json"] }
rocket_sync_db_pools = { version = "0.1.0-rc.2", features = ["diesel_postgres_pool"] }
```

Any ideas? What am I missing?
